# Generated by Django 5.2.5 on 2025-09-18 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PNR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(max_length=20, unique=True)),
                ('office_id', models.CharField(blank=True, max_length=20)),
                ('agent', models.CharField(blank=True, max_length=20)),
                ('creation_date', models.CharField(blank=True, max_length=10)),
                ('creator_iata_code', models.CharField(blank=True, max_length=20)),
                ('delivery_system_company', models.CharField(blank=True, max_length=10)),
                ('delivery_system_location', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('ff_number', models.CharField(blank=True, max_length=20)),
                ('ff_tier', models.CharField(blank=True, max_length=20)),
                ('board_point', models.CharField(blank=True, max_length=10)),
                ('off_point', models.CharField(blank=True, max_length=10)),
                ('seat_row_number', models.CharField(blank=True, max_length=10)),
                ('seat_column', models.CharField(blank=True, max_length=10)),
                ('meal', models.CharField(blank=True, max_length=20)),
                ('pnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='quality_monitor.pnr')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('AP', 'AP'), ('APE', 'APE'), ('APM', 'APM'), ('CTCE', 'CTCE'), ('CTCEM', 'CTCEM'), ('CTCM', 'CTCM')], max_length=10)),
                ('contact_detail', models.CharField(max_length=200)),
                ('pnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='quality_monitor.pnr')),
            ],
        ),
    ]
