# Generated by Django 5.2.5 on 2025-09-19 18:00

from django.db import migrations, models
from datetime import datetime

def forwards_func(apps, schema_editor):
    """
    Convert creation_date from DDMMYY string to DateField.
    """
    PNR = apps.get_model("quality_monitor", "PNR")
    for pnr in PNR.objects.all():
        if pnr.creation_date and isinstance(pnr.creation_date, str):
            try:
                # Assuming the string format is DDMMYY
                pnr.creation_date = datetime.strptime(pnr.creation_date, '%d%m%y').date()
                pnr.save(update_fields=['creation_date'])
            except (ValueError, TypeError):
                # If conversion fails, set it to None
                pnr.creation_date = None
                pnr.save(update_fields=['creation_date'])

class Migration(migrations.Migration):

    dependencies = [
        ('quality_monitor', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pnr',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]