# Generated by Django 5.2.5 on 2025-09-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='agency_iata',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='agency_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_channel',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile App'), ('office', 'Own Office'), ('agency', 'Travel Agency'), ('ndc', 'NDC')], default='web', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='office_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='staff_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='staff_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
