# Generated by Django 5.2.5 on 2025-09-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_monitor', '0002_kqoffice_travelagency_booking_booking_channel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_channel',
        ),
        migrations.AddField(
            model_name='booking',
            name='channel_type',
            field=models.CharField(choices=[('direct', 'Direct'), ('indirect', 'Indirect')], default='direct', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='office_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
