# Generated by Django 5.2.5 on 2025-09-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_monitor', '0003_remove_booking_booking_channel_booking_channel_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='channel_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='office_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='channel',
            field=models.CharField(choices=[('website', 'Website'), ('mobile', 'Mobile'), ('ato', 'ATO'), ('cto', 'CTO'), ('cec', 'Contact Center (CEC)'), ('kq_gsa', 'KQ GSA'), ('travel_agents', 'Travel Agents'), ('ndc', 'NDC'), ('msafiri_connect', 'Msafiri Connect')], default='website', max_length=20),
        ),
    ]
