# Generated by Django 5.2.5 on 2025-09-22 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_monitor', '0003_add_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contact',
            new_name='quality_mon_contact_f693f3_idx',
            old_name='quality_mon_contact_idx',
        ),
        migrations.RenameIndex(
            model_name='pnr',
            new_name='quality_mon_creatio_03250d_idx',
            old_name='quality_mon_creatio_idx',
        ),
        migrations.RenameIndex(
            model_name='pnr',
            new_name='quality_mon_deliver_ff9bbf_idx',
            old_name='quality_mon_deliver_idx',
        ),
    ]
